
module fastdds_soa {

enum ErrorCode {
    SUCCESS,
    SERVICE_NOT_AVAILABLE,
    METHOD_NOT_REGISTER,
    REQUEST_TIMEOUT
};

struct RPC_Header {
    string client_id;
    long session_id;
    long method_id;
    long request_id;
};

struct RPC_Request {
    RPC_Header header;
    string request_payload;
};

struct RPC_Response {
    RPC_Header header;
    ErrorCode error_code;
    string response_payload;
};

};  // fastdds_soa
