CXX = g++
CXXFLAGS = -g3 -Wall -Wextra #-DDEBUG
INCLUDE = 
LDFLAGS = 
LDLIBS = -lpthread

PROGS =	prodcons

.PHONY: all
all: $(PROGS)
	@echo "build OK!"

clean:
	@$(RM) $(PROGS) *.o
	@echo "clean OK!"

prodcons: prodcons.o random.o worker_thread.o
	$(CXX) -o $@ $^ $(LDFLAGS) $(LDLIBS)

